name: Android CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Secure APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Punto 2: Ejecutar pruebas unitarias. Si fallan, el pipeline se detiene.
      - name: Run Unit Tests
        run: ./gradlew test

      # Punto 5: Inyectar certificado desde Secrets
      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > app/release.keystore

      # Punto 4 y 7: Compilar el proyecto de forma automatizada
      - name: Build Release APK
        run: ./gradlew assembleRelease
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      # Punto 6: Nombre del Compilado din√°mico (Proyecto + Build Number)
      - name: Rename APK
        run: |
          cp app/build/outputs/apk/release/app-release.apk MySecureApp-build-${{ github.run_number }}.apk

      # Punto 8: Exportar Artefacto (Publicar para descarga)
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Secure-Android-APK
          path: MySecureApp-build-${{ github.run_number }}.apk
          retention-days: 5
