name: Android CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    name: Build and Secure APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Punto 2: Ejecutar pruebas unitarias. Si fallan, el pipeline se detiene.
      - name: Run Unit Tests
        run: ./gradlew test

      # Punto 5: Inyectar certificado desde Secrets
      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > app/release.keystore

      # Punto 4 y 7: Compilar el proyecto de forma automatizada
      - name: Build Release APK
        run: ./gradlew assembleRelease
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      # Punto 6 y 8 Corregidos: Nombre dinámico tanto en archivo como en artefacto
      - name: Rename APK
        run: |
          cp app/build/outputs/apk/release/app-release.apk MySecureApp-build-${{ github.run_number }}.apk

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MySecureApp-build-${{ github.run_number }}
          path: MySecureApp-build-${{ github.run_number }}.apk
          retention-days: 5

      - name: Create Git Tag
        if: github.event_name == 'push'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Definimos el tag. Ej: v1.0.25
          TAG_NAME="v1.0.${{ github.run_number }}"
          
          echo "Creando tag $TAG_NAME..."
          git tag -a "$TAG_NAME" -m "Automated Release $TAG_NAME"
          git push origin "$TAG_NAME"

      - name: Upload to Firebase App Distribution
        if: github.event_name == 'push'
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          testers: "martinsebastianperezq@gmail.com"
          file: MySecureApp-build-${{ github.run_number }}.apk
          releaseNotes: "Entrega Automática Build #${{ github.run_number }} - Rama: ${{ github.ref_name }}"
