name: Android CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    name: Build and Secure APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Punto 2
      - name: Run Unit Tests
        run: ./gradlew test

      # Punto 5
      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > app/release.keystore

      # Punto 4 y 7
      - name: Build Release APK
        run: ./gradlew assembleRelease
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          BUILD_NUMBER: ${{ github.run_number }}
          GITHUB_SHA: ${{ github.sha }}

      # Punto 6 y 8
      - name: Rename APK
        run: |
          cp app/build/outputs/apk/release/app-release.apk MySecureApp-build-${{ github.run_number }}.apk

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MySecureApp-build-${{ github.run_number }}
          path: MySecureApp-build-${{ github.run_number }}.apk
          retention-days: 5

      - name: Create GitHub Release
        if: github.event_name == 'push'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: "Versión v1.0.${{ github.run_number }}"
          body: |
            ## Secure Release
            Versión compilada y firmada automáticamente por el main pipeline DevSecOps.
            
            ### Detalles Técnicos:
            * **Build ID:** ${{ github.run_number }}
            * **Commit:** ${{ github.sha }}
            * **Rama:** ${{ github.ref_name }}
            
            ### Descarga Directa:
            Lineas abajo se encuentra el archivo `.apk` firmado.
          draft: false
          prerelease: false
          files: MySecureApp-build-${{ github.run_number }}.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload to Firebase App Distribution
        if: github.event_name == 'push'
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          testers: "martinsebastianperezq@gmail.com"
          file: MySecureApp-build-${{ github.run_number }}.apk
          releaseNotes: "Entrega Automática Build #${{ github.run_number }} - Rama: ${{ github.ref_name }}"
